# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.IntegerField(choices=[(0, 'Auto'), (1, 'Motorcycle')], default=0)),
                ('product_type', models.IntegerField(choices=[(0, 'Retail'), (1, 'Lease'), (2, 'Balloon')], default=0)),
                ('deal_type', models.IntegerField(choices=[(0, 'Regular/Digital'), (1, 'Spot')], default=0)),
                ('applicant_type', models.IntegerField(choices=[(0, 'Applicant'), (1, 'Co-Applicant')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LenderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lender',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LenderDetails'),
        ),
        migrations.AddField(
            model_name='lender',
            name='lender_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StateDetails'),
        ),
    ]
